### ISSUE TITLE
Klarna 400 Bad Request response ("Bad value: total_amount") when shipping cost has a decimal.

### ISSUE THREAD

**Issue by isjackwild** [elleracompany/commerce-klarna-checkout#31]
I have integrated Klarna Checkout with Craft Commerce, and I am encountering an error when loading the payment form if I have a shipping cost which is not rounded to a full value.

### Error:
```
Klarna is expecting other values, make sure you've added taxes as described in the documentation for the Klarna Checkout Plugin, and that you've correctly set the Site Base URL. Klarna Response: Client error: `POST https://api.playground.klarna.com/checkout/v3/orders` resulted in a `400 Bad Request` response:
{"error_code":"BAD_VALUE","error_messages":["Bad value: total_amount"],"correlation_id":"eb77be44-fb51-4e1d-be08-5573297 (truncated...)
```

### Example:
- £3 shipping cost works and the Klarna form loads
- £3.50 shipping cost breaks, and when loading the form I get the error.

I have no other conditions (weight / price) in my shipping rule, and my tax settings have been changed to match the Klarna Checkout documentation. I have also ensured that the Site Base URL is set properly.

### Versions
- Craft edition & version | Craft Pro 3.4.16
- Craft Commerce | 3.1.3
- Klarna Checkout for Craft Commerce | 1.1.8

Hopefully this will be a quick fix, as it's quite a blocker for us using (and purchasing) the plugin at the moment.

Thanks in advance!

### Full stack trace
```
yii\base\InvalidConfigException: Klarna is expecting other values, make sure you've added taxes as described in the documentation for the Klarna Checkout Plugin, and that you've correctly set the Site Base URL. Klarna Response: Client error: `POST https://api.playground.klarna.com/checkout/v3/orders` resulted in a `400 Bad Request` response:
{"error_code":"BAD_VALUE","error_messages":["Bad value: total_amount"],"correlation_id":"eb77be44-fb51-4e1d-be08-5573297 (truncated...)
 in /var/www/staging.thestem.co.uk/public_html/vendor/elleracompany/commerce-klarna-checkout/src/gateways/KlarnaCheckout.php:231
Stack trace:
#0 /var/www/staging.thestem.co.uk/public_html/vendor/elleracompany/commerce-klarna-checkout/src/gateways/KlarnaCheckout.php(545): ellera\commerce\klarna\gateways\KlarnaCheckout->authorize(Object(craft\commerce\models\Transaction), Object(ellera\commerce\klarna\models\KlarnaPaymentForm))
#1 /var/www/staging.thestem.co.uk/public_html/vendor/elleracompany/commerce-klarna-checkout/src/gateways/KlarnaCheckout.php(523): ellera\commerce\klarna\gateways\KlarnaCheckout->createCheckoutOrder()
#2 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Extension/CoreExtension.php(1499): ellera\commerce\klarna\gateways\KlarnaCheckout->getPaymentFormHtml(Array)
#3 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ellera\commerce\klarna\gateways\KlarnaCheckout), 'getPaymentFormH...', Array, 'method', false, false)
#4 /var/www/staging.thestem.co.uk/public_html/storage/runtime/compiled_templates/8f/8fb726a393c7bf1c734d5b5b57eb336d222514079454b892f1dfe889655b96ff.php(303): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ellera\commerce\klarna\gateways\KlarnaCheckout), 'getPaymentFormH...', Array, 'method')
#5 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(184): __TwigTemplate_68908c52685967ed37ba76b223a1a2f605d708d3c0a35a892a2f7f7d564eaa27->block_main(Array, Array)
#6 /var/www/staging.thestem.co.uk/public_html/storage/runtime/compiled_templates/5b/5b75eb2d522d9ce63e00e639646cec9df9eda920a24c38c5d7928eff8037b871.php(205): Twig\Template->displayBlock('main', Array, Array)
#7 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ef846342dde8d5594cfd9a5296a7e63bd5f9cba48b1f5d2e8a354207f1e23c5c->doDisplay(Array, Array)
#8 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/staging.thestem.co.uk/public_html/storage/runtime/compiled_templates/8f/8fb726a393c7bf1c734d5b5b57eb336d222514079454b892f1dfe889655b96ff.php(48): Twig\Template->display(Array, Array)
#10 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_68908c52685967ed37ba76b223a1a2f605d708d3c0a35a892a2f7f7d564eaa27->doDisplay(Array, Array)
#11 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#13 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /var/www/staging.thestem.co.uk/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/View.php(397): Twig\Environment->render('checkout/paymen...', Array)
#16 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate('checkout/paymen...', Array)
#17 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('checkout/paymen...', Array, 'site')
#18 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('checkout/paymen...', Array)
#19 [internal function]: craft\controllers\TemplatesController->actionRender('checkout/paymen...', Array)
#20 /var/www/staging.thestem.co.uk/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /var/www/staging.thestem.co.uk/public_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#22 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#23 /var/www/staging.thestem.co.uk/public_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#24 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#25 /var/www/staging.thestem.co.uk/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#26 /var/www/staging.thestem.co.uk/public_html/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#27 /var/www/staging.thestem.co.uk/public_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /var/www/staging.thestem.co.uk/public_html/web/index.php(22): yii\base\Application->run()
#29 {main}

```

**Comment by jellingsen** [comment]
Hi,

This should now be fixed with v1.1.9.
